"""add lead deep analysis fields

Revision ID: d42ac67cf3ec
Revises: be41d6004fb6
Create Date: 2026-09-07 10:01:11.172037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd42ac67cf3ec'
down_revision: Union[str, Sequence[str], None] = 'be41d6004fb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_leads', sa.Column('jd_text', sa.Text(), nullable=True))
    op.add_column('job_leads', sa.Column('deep_ok', sa.Integer(), server_default='0', nullable=False))
    op.add_column('job_leads', sa.Column('deep_part', sa.Integer(), server_default='0', nullable=False))
    op.add_column('job_leads', sa.Column('deep_total', sa.Integer(), server_default='0', nullable=False))
    op.add_column('job_leads', sa.Column('report_id', sa.Integer(), nullable=True))
    op.add_column('job_leads', sa.Column('deep_at', sa.DateTime(), nullable=True))
    with op.batch_alter_table('job_leads') as batch_op:
        batch_op.create_foreign_key('fk_lead_report', 'saved_reports', ['report_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_leads') as batch_op:
        batch_op.drop_constraint('fk_lead_report', type_='foreignkey')
    op.drop_column('job_leads', 'deep_at')
    op.drop_column('job_leads', 'report_id')
    op.drop_column('job_leads', 'deep_total')
    op.drop_column('job_leads', 'deep_part')
    op.drop_column('job_leads', 'deep_ok')
    op.drop_column('job_leads', 'jd_text')
    # ### end Alembic commands ###
